{{- if .Values.secrets.caCerts.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: ca-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  "ca.crt": |
{{- .Values.secrets.caCerts.certs | nindent 4 }}
{{- end }}