apiVersion: v1
kind: ConfigMap
metadata:
  name: cleaner-config
  namespace: rancher-node-cleaner
data:
  CLUSTER_IDS: {{ .Values.config.rancher.clusterId | quote }}
  POLL_SECONDS: {{ .Values.config.pollingSeconds | quote }}
  GRACE_SECONDS: {{ .Values.config.graceSeconds | quote }}
  DRY_RUN: {{ .Values.config.dryRun | quote }}
  AWS_REGION: {{ .Values.config.rancher.awsRegion | quote }}