apiVersion: batch/v1
kind: CronJob
metadata:
  name: rancher-node-cleaner
  namespace: {{ .Values.namespace }}
spec:
  schedule: {{ .Values.cron.schedule }}
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 5
  jobTemplate:
    spec:
      backoffLimit: 2
      template:
        spec:
          {{- if .Values.image.imagePullSecrets }}
          imagePullSecrets:
          {{- toYaml .Values.imagePullSecrets | nindent 10 }}
          {{- end }}
          serviceAccountName: rancher-node-cleaner
          restartPolicy: Never
          securityContext:
            runAsNonRoot: true
            runAsUser: 10001
            runAsGroup: 10001
            fsGroup: 10001
          containers:
            - name: node-cleaner
              image: {{ .Values.image.repository }}:{{ .Values.image.tag}}
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              envFrom:
                - secretRef:
                    name: rancher-node-cleaner
              env:
                {{- if and .Values.secrets.caCerts.enabled .Values.secrets.caCerts.certs }}
                - name: REQUESTS_CA_BUNDLE
                  value: "/etc/ssl/custom/ca-certificates.crt"
                {{- end }}
              args:
                {{- if .Values.config.verbose }}
                  - "--verbose"
                {{- end }}
                {{- if .Values.config.dryRun }}
                - "--dry-run"
                {{- end }}
                {{- if .Values.config.rancher.insecureSkipTlsVerify }}
                - "--insecure-skip-tls-verify"
                {{- end }}
              resources:
                {{- toYaml .Values.resources | nindent 12 }}
              securityContext:
                allowPrivilegeEscalation: false
                readOnlyRootFilesystem: true
                capabilities:
                  drop: ["ALL"]
              {{- if and .Values.secrets.caCerts.enabled .Values.secrets.caCerts.certs }}
              volumeMounts:
                - name: ca-secret
                  mountPath: /etc/ssl/custom/ca-certificates.crt
                  subPath: ca-certificates.crt
                  readOnly: true
              {{- end }}
          {{- if and .Values.secrets.caCerts.enabled .Values.secrets.caCerts.certs }}
          volumes:
            - name: ca-secret
              secret:
                secretName: ca-secret
          {{- end }}