apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: rancher-node-cleaner
  namespace: {{ .Values.namespace }}
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["rancher-node-cleaner"]
    verbs: ["get"]