{{- if .Values.secrets.rancher.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: rancher-api
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  RANCHER_URL: {{ .Values.config.rancher.url | quote}}
  RANCHER_TOKEN: {{ .Values.config.rancher.token | quote}}
{{- end }}