namespace: kube-system

replicas: 2

image:
  repository: "rancher-node-cleaner"
  tag: "latest"
  pullPolicy: Always
  imagePullSecrets:

config:
  dryRun: true
  pollingSeconds: 30
  graceSeconds: 180
  rancher:
    url: "https://rancher.example.com"
    token: ""
    clusterId: "c-m-abcde"
    awsRegion: "us-east-1"
    insecureSkipTlsVerify: true

resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi

secrets:
  rancher:
    enabled: false
  caCerts:
    enabled: false
    certs: